#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# basic X environment
#twm &
#xclock -geometry 50x50-1+1 &
#xterm -geometry 80x50+494+51 &
#xterm -geometry 80x20+494-0 &
#exec xterm -geometry 80x66+0+0 -name login
xbindkeys

if [ `xrandr | grep -c ' connected '` -eq 2 ]; then
    xrandr --output HDMI2 --auto --right-of eDP1
    feh --bg-scale Pictures/wallpaper/arch_wallpaper.png --bg-scale Pictures/wallpaper/arch_wallpaper.png
else
    feh --bg-scale Pictures/wallpaper/arch_wallpaper.png
fi
    
#conky | while read -r; do xsetroot -name "$(date +"%a %b %d %I:%M%P");$REPLY"; done & 
while true; do
    xsetroot -name "$(date +"%a %b %d %I:%M%P")"
    sleep 10s
done &
conky

exec dwm
